// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlIsmMjOfOQrceZLz4S8KA2WXcGBW4WDM',
    appId: '1:285749107281:web:ae241bccd729777676b670',
    messagingSenderId: '285749107281',
    projectId: 'memococktail-1454c',
    authDomain: 'memococktail-1454c.firebaseapp.com',
    storageBucket: 'memococktail-1454c.firebasestorage.app',
    measurementId: 'G-ZV9H5HT0QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfP-qwJHm0XAkNLsJCBVjSqo0UNLtYNgs',
    appId: '1:285749107281:android:8c8c422c7b30448576b670',
    messagingSenderId: '285749107281',
    projectId: 'memococktail-1454c',
    storageBucket: 'memococktail-1454c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNPRYUi7Jv_P1KNdcSKTCMn8ckr41o0iU',
    appId: '1:285749107281:ios:db0f434bb4795c2e76b670',
    messagingSenderId: '285749107281',
    projectId: 'memococktail-1454c',
    storageBucket: 'memococktail-1454c.firebasestorage.app',
    iosBundleId: 'com.testing.prova1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNPRYUi7Jv_P1KNdcSKTCMn8ckr41o0iU',
    appId: '1:285749107281:ios:bb492300c1dba0a376b670',
    messagingSenderId: '285749107281',
    projectId: 'memococktail-1454c',
    storageBucket: 'memococktail-1454c.firebasestorage.app',
    iosBundleId: 'com.example.prova1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlIsmMjOfOQrceZLz4S8KA2WXcGBW4WDM',
    appId: '1:285749107281:web:f9516cac94297f4e76b670',
    messagingSenderId: '285749107281',
    projectId: 'memococktail-1454c',
    authDomain: 'memococktail-1454c.firebaseapp.com',
    storageBucket: 'memococktail-1454c.firebasestorage.app',
    measurementId: 'G-309ZEGTM03',
  );
}
